/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Booklets {
  disciplines: Generated<Json>;
  district_id: number | null;
  exam_id: number;
  grade: number;
  id: Generated<number>;
  legacy_mongo_id: string | null;
  name: string | null;
  variant: string;
}

// Добавлено вручную вслед за миграцией 004_code_change_log.sql — перегенерировать через
// kysely-codegen при следующей возможности подключиться к живой БД и сверить.
export interface CodeChangeLogs {
  caused_by_entity_id: number | null;
  caused_by_entity_type: string | null;
  changed_at: Generated<Timestamp>;
  changed_by: number;
  entity_id: number;
  entity_type: string;
  id: Generated<number>;
  new_code: number;
  old_code: number;
}

export interface Districts {
  active: Generated<boolean>;
  avatar_url: string | null;
  code: number;
  district_of_the_year_score: Generated<number | null>;
  education_head_name: string | null;
  id: Generated<number>;
  legacy_mongo_id: string | null;
  name: string;
  rate: number | null;
  region_id: number | null;
  student_count: number | null;
}

export interface DistrictYearRatings {
  average_score: number | null;
  district_id: number;
  place: number | null;
  score: number | null;
  year: number;
}

export interface Exams {
  active: Generated<boolean>;
  code: number;
  date: Timestamp;
  id: Generated<number>;
  legacy_mongo_id: string | null;
  name: string;
}

export interface GradePromotionLogs {
  academic_year: number;
  ceiling_count: number | null;
  completed_at: Timestamp | null;
  executed_at: Generated<Timestamp>;
  executed_by: number;
  id: Generated<number>;
  legacy_mongo_id: string | null;
  promoted_count: number | null;
  status: Generated<string>;
}

// Добавлено вручную вслед за миграцией 015_academic_year_closures.sql — перегенерировать через
// kysely-codegen при следующей возможности подключиться к живой БД и сверить.
export interface AcademicYearClosures {
  academic_year: number;
  checksums: Generated<Json>;
  closed_at: Generated<Timestamp>;
  closed_by: number | null;
  closed_reason: Generated<string>;
  note: string | null;
}

// Добавлено вручную вслед за миграцией 011_certificates.sql — перегенерировать через
// kysely-codegen при следующей возможности подключиться к живой БД и сверить.
export interface CertificateTemplates {
  active: Generated<boolean>;
  award_code: string;
  created_at: Generated<Timestamp>;
  fields: Generated<Json>;
  id: Generated<number>;
  image_height: number;
  image_path: string;
  image_width: number;
  level_code: string | null;
  name: string;
  updated_at: Generated<Timestamp>;
}

// Добавлено вручную вслед за миграцией 011_certificates.sql — перегенерировать через
// kysely-codegen при следующей возможности подключиться к живой БД и сверить.
export interface IssuedCertificates {
  award_code: string;
  data: Json;
  id: Generated<number>;
  image_height: number;
  image_path: string;
  image_width: number;
  issued_at: Generated<Timestamp>;
  layout: Json;
  revoke_reason: string | null;
  revoked_at: Timestamp | null;
  serial: string;
  student_result_id: number;
  template_id: number;
  verify_token: string;
}

// Добавлено вручную вслед за миграцией 005_regions.sql — перегенерировать через
// kysely-codegen при следующей возможности подключиться к живой БД и сверить.
export interface Regions {
  active: Generated<boolean>;
  avatar_url: string | null;
  code: number;
  id: Generated<number>;
  name: string;
  region_of_the_year_score: Generated<number | null>;
}

export interface RegionYearRatings {
  average_score: number | null;
  place: number | null;
  region_id: number;
  score: number | null;
  year: number;
}

export interface Levels {
  active: Generated<boolean>;
  code: string;
  max_total_score: number | null;
  min_total_score: number;
  name_az: string;
  participation_score: number;
  rank: number;
}

// Добавлено вручную вслед за миграцией 017_profile_change_requests.sql — перегенерировать через
// kysely-codegen при следующей возможности подключиться к живой БД и сверить.
export interface ProfileChangeRequests {
  entity_id: number;
  entity_type: string;
  id: Generated<number>;
  payload: Json;
  review_note: string | null;
  reviewed_at: Timestamp | null;
  reviewed_by: number | null;
  status: Generated<string>;
  submitted_at: Generated<Timestamp>;
  submitted_by: number;
}

export interface Schools {
  achievements: string | null;
  active: Generated<boolean>;
  address: string | null;
  avatar_url: string | null;
  code: number;
  description: string | null;
  director_name: string | null;
  district_id: number;
  founded_year: number | null;
  history: string | null;
  id: Generated<number>;
  legacy_mongo_id: string | null;
  name: string;
  school_of_the_year_score: Generated<number | null>;
  status: string | null;
  student_count: number | null;
}

export interface SchemaMigrations {
  applied_at: Generated<Timestamp>;
  filename: string;
}

export interface SchoolYearRatings {
  average_score: number | null;
  district_place: number | null;
  place: number | null;
  school_id: number;
  score: number | null;
  year: number;
}

export interface StudentResults {
  academic_year: Generated<number | null>;
  az: number;
  az_count: number;
  development_score: number | null;
  english: number | null;
  english_count: number | null;
  exam_id: number | null;
  grade: number;
  id: Generated<number>;
  legacy_mongo_id: string | null;
  level: string;
  life_knowledge: number | null;
  life_knowledge_count: number | null;
  logic: number | null;
  logic_count: number | null;
  math: number;
  math_count: number;
  month: number;
  participation_score: number;
  republic_wide_student_of_the_month_score: number | null;
  score: number;
  status: string | null;
  student_id: number;
  student_of_the_month_score: number | null;
  total_score: number;
  year: number;
}

export interface Students {
  avatar_url: string | null;
  code: number;
  district_id: number | null;
  first_name: string;
  grade: number | null;
  id: Generated<number>;
  last_name: string | null;
  legacy_mongo_id: string | null;
  max_level: number | null;
  middle_name: string | null;
  school_id: number | null;
  status: string | null;
  teacher_id: number | null;
}

export interface StudentYearRatings {
  average_score: number | null;
  district_place: number | null;
  place: number | null;
  score: number | null;
  student_id: number;
  year: number;
}

// Добавлено вручную вслед за миграцией 018_student_grade_history.sql — перегенерировать через
// kysely-codegen при следующей возможности подключиться к живой БД и сверить.
export interface StudentGradeHistory {
  academic_year: number;
  grade: number;
  student_id: number;
}

export interface Subjects {
  active: Generated<boolean>;
  code: string;
  count_column: string;
  max_grade: number | null;
  min_grade: number | null;
  name_az: string;
  result_column: string;
  sort_order: number;
}

export interface Teachers {
  achievements: string | null;
  active: Generated<boolean>;
  avatar_url: string | null;
  biography: string | null;
  code: number;
  district_id: number | null;
  fullname: string;
  grade_label: string | null;
  id: Generated<number>;
  legacy_mongo_id: string | null;
  pedagogical_experience_years: number | null;
  pedagogical_start_year: number | null;
  school_id: number | null;
  status: string | null;
  student_count: number | null;
  teacher_of_the_year_score: Generated<number | null>;
}

export interface TeacherYearRatings {
  average_score: number | null;
  district_place: number | null;
  place: number | null;
  score: number | null;
  teacher_id: number;
  year: number;
}

export interface UserRefreshTokens {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  token: string;
  user_id: number;
}

export interface Users {
  created_at: Generated<Timestamp>;
  district_id: number | null;
  email: string;
  id: Generated<number>;
  is_approved: Generated<boolean>;
  last_login_at: Timestamp | null;
  legacy_mongo_id: string | null;
  password_hash: string;
  region_id: number | null;
  role: Generated<string>;
  school_id: number | null;
  student_id: number | null;
  teacher_id: number | null;
  updated_at: Generated<Timestamp>;
}

export interface UserSettings {
  all_district_collumns: Generated<string[]>;
  all_region_collumns: Generated<string[]>;
  all_school_collumns: Generated<string[]>;
  all_student_collumns: Generated<string[]>;
  all_teacher_collumns: Generated<string[]>;
  created_at: Generated<Timestamp>;
  developing_student_collumns: Generated<string[]>;
  director_view_collumns: Generated<string[]>;
  district_view_collumns: Generated<string[]>;
  id: Generated<number>;
  role_settings: Generated<Json>;
  student_collumns: Generated<string[]>;
  student_view_collumns: Generated<string[]>;
  teacher_view_collumns: Generated<string[]>;
  updated_at: Generated<Timestamp>;
  user_id: number | null;
}

export interface VDistrictPlaces {
  academic_year: number | null;
  district_id: number | null;
  place: number | null;
}

export interface VDistrictYearScores {
  academic_year: number | null;
  average_score: number | null;
  district_id: number | null;
  score: number | null;
}

export interface VRegionYearScores {
  academic_year: number | null;
  average_score: number | null;
  region_id: number | null;
  score: number | null;
  students_in_region: number | null;
}

export interface VRegionPlaces {
  academic_year: number | null;
  place: number | null;
  region_id: number | null;
}

export interface VSchoolPlaces {
  academic_year: number | null;
  district_place: number | null;
  place: number | null;
  school_id: number | null;
}

export interface VSchoolYearScores {
  academic_year: number | null;
  average_score: number | null;
  school_id: number | null;
  score: number | null;
}

export interface VStudentPlaces {
  academic_year: number | null;
  district_place: number | null;
  place: number | null;
  student_id: number | null;
}

export interface VStudentResultSubjectScores {
  academic_year: number | null;
  exam_id: number | null;
  grade: number | null;
  question_count: number | null;
  result_id: number | null;
  score: number | null;
  student_id: number | null;
  subject_code: string | null;
}

export interface VStudentYearScores {
  academic_year: number | null;
  average_score: number | null;
  development_score: number | null;
  participation_count: number | null;
  participation_score: number | null;
  republic_wide_student_of_the_month_score: number | null;
  score: number | null;
  student_id: number | null;
  student_of_the_month_score: number | null;
}

export interface VTeacherPlaces {
  academic_year: number | null;
  district_place: number | null;
  place: number | null;
  teacher_id: number | null;
}

export interface VTeacherYearScores {
  academic_year: number | null;
  average_score: number | null;
  score: number | null;
  teacher_id: number | null;
}

export interface DB {
  academic_year_closures: AcademicYearClosures;
  booklets: Booklets;
  certificate_templates: CertificateTemplates;
  code_change_logs: CodeChangeLogs;
  district_year_ratings: DistrictYearRatings;
  districts: Districts;
  exams: Exams;
  grade_promotion_logs: GradePromotionLogs;
  issued_certificates: IssuedCertificates;
  levels: Levels;
  profile_change_requests: ProfileChangeRequests;
  region_year_ratings: RegionYearRatings;
  regions: Regions;
  schema_migrations: SchemaMigrations;
  school_year_ratings: SchoolYearRatings;
  schools: Schools;
  student_grade_history: StudentGradeHistory;
  student_results: StudentResults;
  student_year_ratings: StudentYearRatings;
  students: Students;
  subjects: Subjects;
  teacher_year_ratings: TeacherYearRatings;
  teachers: Teachers;
  user_refresh_tokens: UserRefreshTokens;
  user_settings: UserSettings;
  users: Users;
  v_district_places: VDistrictPlaces;
  v_district_year_scores: VDistrictYearScores;
  v_region_places: VRegionPlaces;
  v_region_year_scores: VRegionYearScores;
  v_school_places: VSchoolPlaces;
  v_school_year_scores: VSchoolYearScores;
  v_student_places: VStudentPlaces;
  v_student_result_subject_scores: VStudentResultSubjectScores;
  v_student_year_scores: VStudentYearScores;
  v_teacher_places: VTeacherPlaces;
  v_teacher_year_scores: VTeacherYearScores;
}
